// 用户可见文案唯一负责点（中文单语起步；双语决策待定，见 docs/core/DECISIONS.md D5 之外的语言口径说明）。
// 口径：控件短句、状态与错误都以这里为唯一来源，避免文案散落各 UI 文件。

export const STR = {
	commandOpen: "打开额度面板",
	ribbonTooltip: "AI 编程套餐额度",
	panelTitle: "AI 编程套餐额度",
	refreshAll: "全部刷新",
	refresh: "刷新",
	expandAll: "全部展开",
	collapseAll: "全部收起",
	loading: "查询中…",
	noAccounts: "还没有账号，先到设置里添加一个。",
	openSettings: "打开设置",
	capturedAt: "更新",
	settingsHeading: "账号",
	addAccount: "添加账号",
	accountEmpty: "暂无账号。点击「添加账号」接入第一个套餐。",
	delete: "删除",
	wizardTitle: "添加账号",
	wizardProvider: "套餐来源",
	wizardAlias: "账号别名",
	wizardAliasPlaceholder: "例如：OC·主号",
	wizardCredential: "凭证",
	wizardTestAndSave: "测试并保存",
	wizardCancel: "取消",
	wizardTesting: "测试中…",
	wizardSave: "保存",
	editAccount: "编辑账号",
	edit: "编辑",
	credentialEditHint: "修改后保存时会重新验证新凭证",
	revealKey: "切换明文显示",
	savedOk: "已保存",
	secretMissing: "凭证丢失或未找到，请到设置里重新填写。",
	deleteConfirmPrefix: "删除账号",
	deleteConfirmSuffix: "？（凭证将一并清除）",
	fetchFailedPrefix: "查询失败",
	httpPrefix: "HTTP",
	planName: "套餐",
	testOk: "连接成功",
} as const;
