// 用户可见文案唯一负责点（中文单语起步；双语决策待定，见 docs/core/DECISIONS.md D5 之外的语言口径说明）。
// 口径：控件短句、状态与错误都以这里为唯一来源，避免文案散落各 UI 文件。

export const STR = {
	commandOpen: "打开额度面板",
	ribbonTooltip: "AI 编程套餐额度",
	panelTitle: "AI 编程套餐额度",
	refreshAll: "全部刷新",
	refresh: "刷新",
	expandAll: "全部展开",
	collapseAll: "全部收起",
	sortBy: "排序",
	sortProviderAsc: "套餐 (A-Z)",
	sortProviderDesc: "套餐 (Z-A)",
	sortUsageDesc: "用量 (从多到少)",
	sortUsageAsc: "用量 (从少到多)",
	sortResetAsc: "重置时间 (从近到远)",
	sortResetDesc: "重置时间 (从远到近)",
	loading: "查询中…",
	noAccounts: "还没有账号，先到设置里添加一个。",
	openSettings: "打开设置",
	capturedAt: "更新",
	accountsTitle: "已接入账号",
	addAccount: "添加账号",
	accountEmpty: "暂无账号。点击「添加账号」接入第一个套餐。",
	delete: "删除",
	wizardTitle: "添加账号",
	wizardProvider: "套餐来源",
	wizardAlias: "账号别名",
	wizardAliasPlaceholder: "例如：OC·主号",
	wizardCredential: "凭证",
	wizardTestAndSave: "测试并保存",
	wizardCancel: "取消",
	wizardTesting: "测试中…",
	wizardSave: "保存",
	editAccount: "编辑账号",
	edit: "编辑",
	credentialEditHint: "修改后保存时会重新验证新凭证",
	revealKey: "切换明文显示",
	savedOk: "已保存",
	secretMissing: "凭证丢失或未找到，请到设置里重新填写。",
	deleteConfirmPrefix: "删除账号",
	deleteConfirmSuffix: "？（凭证将一并清除）",
	fetchFailedPrefix: "查询失败",
	httpPrefix: "HTTP",
	planName: "套餐",
	testOk: "连接成功",
	// 凭证导出（20260920 三次拍板：弃用「同步」一词——多义易惑；直白口径为把账号与密钥信息导出到缓存、再从其他设备导入）。
	exportHeading: "凭证导出",
	exportCopyName: "导出加密副本",
	exportDescOff:
		"开启后，各账号凭证会加密成副本随插件数据保存，其他设备打开同一库时，在面板首次查看输入口令即可还原；凭证本体仍受系统安全保护，不会直接复制。",
	exportDescOn: "已开启：{n} 个账号的加密副本随插件数据保存，其他设备打开同一库即可还原。",
	exportPassName: "导出口令",
	exportPassDesc: "更换口令或新增账号后，点「更新副本」重新生成全部加密副本；口令本身不保存，遗忘后需重新导出。",
	exportPlaceholder: "至少 8 位",
	exportEnable: "开启导出",
	exportUpdate: "更新副本",
	exportTooShort: "口令至少 8 位",
	exportPassTitle: "设置导出口令",
	exportPassModalDesc: "口令用于加密凭证副本，本身不保存，遗忘后需重新导出。",
	exportDone: "已导出加密副本",
	exportUpdated: "副本已更新",
	exportDisabled: "已关闭导出，加密副本已清除",
	exportStale: "凭证已更新，加密副本已失效，请在设置中重新导出",
	decryptFailed: "口令不正确，请重试",
	unlockTitle: "输入导出口令",
	unlockName: "导出口令",
	unlockDesc: "解锁后本次使用期间不再询问",
	unlockConfirm: "解锁",
} as const;
