// 用户可见文案唯一负责点（中文单语起步；双语决策待定，见 docs/core/DECISIONS.md D5 之外的语言口径说明）。
// 口径：控件短句、状态与错误都以这里为唯一来源，避免文案散落各 UI 文件。

export const STR = {
	commandOpen: "打开额度面板",
	ribbonTooltip: "AI 编程套餐额度",
	panelTitle: "AI 编程套餐额度",
	refreshAll: "全部刷新",
	refresh: "刷新",
	expandAll: "全部展开",
	collapseAll: "全部收起",
	sortBy: "排序",
	sortProviderAsc: "套餐 (A-Z)",
	sortProviderDesc: "套餐 (Z-A)",
	sortUsageDesc: "用量 (从多到少)",
	sortUsageAsc: "用量 (从少到多)",
	sortResetAsc: "重置时间 (从近到远)",
	sortResetDesc: "重置时间 (从远到近)",
	loading: "查询中…",
	noAccounts: "还没有账号，先到设置里添加一个。",
	openSettings: "打开设置",
	capturedAt: "更新",
	settingsHeading: "账号",
	addAccount: "添加账号",
	accountEmpty: "暂无账号。点击「添加账号」接入第一个套餐。",
	delete: "删除",
	wizardTitle: "添加账号",
	wizardProvider: "套餐来源",
	wizardAlias: "账号别名",
	wizardAliasPlaceholder: "例如：OC·主号",
	wizardCredential: "凭证",
	wizardTestAndSave: "测试并保存",
	wizardCancel: "取消",
	wizardTesting: "测试中…",
	wizardSave: "保存",
	editAccount: "编辑账号",
	edit: "编辑",
	credentialEditHint: "修改后保存时会重新验证新凭证",
	revealKey: "切换明文显示",
	savedOk: "已保存",
	secretMissing: "凭证丢失或未找到，请到设置里重新填写。",
	deleteConfirmPrefix: "删除账号",
	deleteConfirmSuffix: "？（凭证将一并清除）",
	fetchFailedPrefix: "查询失败",
	httpPrefix: "HTTP",
	planName: "套餐",
	testOk: "连接成功",
	mobileSyncHeading: "移动端同步",
	mobileSyncName: "同步口令",
	mobileSyncDescOff:
		"生成口令加密的凭证副本随 data.json 同步，手机首次查看时输入口令解锁；口令不落盘，遗忘只能重新生成副本。",
	mobileSyncDescOn: "已启用：{n} 个账号有密文副本。修改口令将重新加密全部副本；凭证更新后副本自动失效需重建。",
	mobileSyncPlaceholder: "同步口令（至少 8 位）",
	mobileSyncApply: "生成副本",
	mobileSyncClear: "清除副本",
	mobileSyncTooShort: "口令至少 8 位",
	mobileSyncApplied: "密文副本已生成，同步 data.json 后手机可用",
	mobileSyncCleared: "密文副本已清除",
	mobileSyncStale: "凭证已更新：移动端密文副本已失效，请到设置重新生成",
	decryptFailed: "解密失败：口令不正确或密文已损坏",
	unlockTitle: "移动端解锁",
	unlockName: "同步口令",
	unlockConfirm: "解锁",
} as const;
